### ISSUE TITLE
Locking and unlocking separately (without a block)

### ISSUE THREAD

**Issue by brendon** [ClosureTree/with_advisory_lock#102]
I've had a good rummage through the code, and am pretty sure things aren't wired up this way, but I wondered if it's possible to kick off a lock with one method call, then release the lock with another? This would be useful say in a `before_save` and `after_save_commit` callback arrangement.

**Comment by nhorton** [comment]
Seconding the ask here. We have a case where we need to take multiple advisory locks, and I hate to make the stack ugly with lots of nested blocks.

**Comment by brendon** [comment]
I ended up integrating my own take on it. You're welcome to see if it works for you:

https://github.com/brendon/positioning/blob/main/lib/positioning/advisory_lock.rb
