### ISSUE TITLE
Drop dependency on thread_safe

### ISSUE THREAD

**Issue by fernandoluizao** [ClosureTree/with_advisory_lock#26]
Hi,

I was wondering why the gem thread_safe is listed as a runtime dependency in the gemspec... Inspecting the code I see no usage of this gem... Could it be removed? This gem was merged into concurrent-ruby and is deprecated.

**Comment by mceachen** [comment]
I just reviewed the commit that added the runtime dependency. It may have been to make an ancient ruby/active_record combination pass in CI, but that time has long passed. 

I'll happily merge a PR that removes this. Thanks for the catch!

**Comment by fernandoluizao** [comment]
Could you release a new version please?

**Comment by mceachen** [comment]
Just pushed v3.2.0 -- thanks again.
