### ISSUE TITLE
undefined method `with_advisory_lock' in Rails test environment

### ISSUE THREAD

**Issue by abinoda** [ClosureTree/with_advisory_lock#34]
I am having difficulty executing `with_advisory_lock` in my Rails test environment:

```
code/pullreminders » rails c
Loading development environment (Rails 5.1.6)
Nirb(main):001:0> NotificationRule.with_advisory_lock
Traceback (most recent call last):
        1: from (irb):1
ArgumentError (wrong number of arguments (given 0, expected 1..2))
irb(main):002:0> exit

code/pullreminders » RAILS_ENV=test rails c
Loading test environment (Rails 5.1.6)
irb(main):001:0> NotificationRule.with_advisory_lock
Traceback (most recent call last):
        1: from (irb):1
NoMethodError (undefined method `with_advisory_lock' for #<Class:0x00007f9769d8d080>)
```

Gemfile:

```
ruby '2.5.0'
gem 'rails', '~> 5.1.6'
gem 'with_advisory_lock', '~> 4.0.0'
```

**Comment by mceachen** [comment]
Without sharing your repo (and specifically your db config) this isn't reproducible. Please look at the test directory for lots of usage examples for every supported db.

**Comment by abinoda** [comment]
@mceachen This is using Postgres, what other information could I provide? I did reference the test directory – I'm wondering if this is some kind of an issue with lazy loading not working in Rails test environment? I can't find any documentation or issues related to this online though.

**Comment by abinoda** [comment]
@mceachen Also updated my original post for a little more clarity.

**Comment by abinoda** [comment]
@mceachen Figured it out. This is a great library by the way, thanks for maintaining it!

**Comment by mceachen** [comment]
What was the issue? Documenting it now might help Engineers of Tomorrow.

**Comment by abinoda** [comment]
Wish I knew. I restarted postgres (for a different reason) and when I came
back my tests worked.
