### ISSUE TITLE
Next planned release?

### ISSUE THREAD

**Issue by seanhandley** [ClosureTree/with_advisory_lock#37]
Hello maintainers,

I'm working on a feature that would very much benefit from nested advisory locks. Currently I'm including this gem by specifying the ref of HEAD of master branch (currently `25e415c`).

Is there a planned release coming up? Our testing so far is successful - it seems stable and reliable - but it's always preferable to be able to lock into a specific release than directly to a commit.

Thanks!

**Comment by mceachen** [comment]
Hey there! We're actually looking for people to [help with the care and feeding](https://github.com/ClosureTree/closure_tree/issues/277) of closure_tree and with_advisory_lock. If you'd like to help, we'd appreciate it. cc/ @seuros

**Comment by seuros** [comment]
@seanhandley 
I created milestones with their release date : https://github.com/ClosureTree/with_advisory_lock/milestones

We could release earlier if there is a stable major version of activerecord released.

**Comment by seanhandley** [comment]
Thanks @seuros @mceachen 👍 

That perfectly answers my question.

**Comment by mceachen** [comment]
@seuros I didn't notice you set up milestones. #prostyle :100:
