### ISSUE TITLE
Rails 6 compatibility?

### ISSUE THREAD

**Issue by brandoncc** [ClosureTree/with_advisory_lock#39]
Hi, and thanks for this gem that looks to be the answer to my problem.

ActiveRecord 6 is not mentioned in the README, are the known issues, or is it not updated yet?

**Comment by seuros** [comment]
There is no issue in ActiveRecord 6.0 reported on the updated application.
I will update the readme and the test suite later this weekend.

**Comment by brandoncc** [comment]
Awesome, thanks again this gem!
