### ISSUE TITLE
Connection pool causing locks to be taken when they shouldn't

### ISSUE THREAD

**Issue by mikebaldry** [ClosureTree/with_advisory_lock#45]
During testing I found that (at least in my set up), ActiveRecord was re-using connections in which advisory locks were held, so when trying to lock on one again, even though it is locked, as it is within the same session. 

I'm not sure if I'm doing something wrong but I can't guarantee the connection that is used to take the lock, so I can't guarantee this is locking correctly all the time.

Can anyone shed some light on to this issue?

**Comment by seuros** [comment]
Version of AR and database type/version will be helpful.
