### ISSUE TITLE
Lots of duplicate/unnecessary calls to `select get_version()`

### ISSUE THREAD

**Issue by joevandyk** [ClosureTree/with_advisory_lock#46]
I believe `select get_version()` gets called on every lock - is that necessary?

https://github.com/ClosureTree/with_advisory_lock/blob/478059f8c436702217108e4136e96b7cd8f16080/lib/with_advisory_lock/database_adapter_support.rb#L24

**Comment by seuros** [comment]
This was fixed in latest version of the gem. We don't support mysql prior 5.7.14 anymore.
