### ISSUE TITLE
Is the unique column name still necessary or does AR do the right thing now?

### ISSUE THREAD

**Issue by wagenet** [ClosureTree/with_advisory_lock#48]
It looks like the code was added 7 years ago, so I could easily believe that it is fixed.

**Comment by wagenet** [comment]
For instance, `uncached` would also seem to handle it https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/QueryCache.html#method-i-uncached

**Comment by seuros** [comment]
Can you point the code here ?

**Comment by wagenet** [comment]
@seuros https://github.com/ClosureTree/with_advisory_lock/blob/478059f8c436702217108e4136e96b7cd8f16080/lib/with_advisory_lock/base.rb#L99-L102

**Comment by rpeng** [comment]
🙏 @seuros Any progress with this request? We had to patch it as it was causing some issues with query metrics, since this gem was generating a ton of unique queries.

**Comment by seuros** [comment]
I will release the new version this weekend hopefully.
