### ISSUE TITLE
[Question] RDSProxy Usage

### ISSUE THREAD

**Issue by eni9889** [ClosureTree/with_advisory_lock#51]
Has anyone used this gem with RDSProxy? Doing testing locally it seems that the locking works properly but I'm not sure if I'm missing something.

**Comment by seuros** [comment]
It should work. I have it with postgresql.
But checkout the documentation of AWS they write something about mysql `Explicit MySQL statements LOCK TABLE, LOCK TABLES, or FLUSH TABLES WITH READ LOCK cause the proxy to pin the session.`

**Comment by eni9889** [comment]
I should have been more clear and mentioned that I am using Postgres. That is good to hear will give it a shot in our staging env.
