### ISSUE TITLE
Why not raise exception when the lock couldn't be acquired in the given timeout?

### ISSUE THREAD

**Issue by sullerandras** [ClosureTree/with_advisory_lock#53]
I know that this is documented behaviour but it trips me over every time when i use this gem. I think it would be more sensible to raise an error if it couldn't acquire the lock, instead of simply not executing the block. The caller could handle the exception if executing the block was optional.

**Comment by seuros** [comment]
Fair point. You wanna take a it  ?

**Comment by jatindhankhar** [comment]
Needed something similar, wrote a wrapper over the`advisory_lock` to achieve to this 

```ruby
module AdvisoryLockManager
  class LockAcquireError < StandardError; end

  def self.with_lock!(lock_id, opts, &block)
    raise LockAcquireError.new("Failed to acquire error for #{lock_id}") unless with_lock(lock_id, opts, &block)
  end

  def self.with_lock(lock_id, opts = {}, &block)
    ActiveRecord::Base.with_advisory_lock(lock_id, opts) do
      yield
    end
  end
end
```

Use it like this 

```ruby
AdvisoryLockManager.with_lock!("hachi",{timeout_seconds: 1}) { sleep 10 }
```

![Screenshot 2022-11-23 at 6 41 21 PM](https://user-images.githubusercontent.com/2412081/203555343-37ff51d4-3c66-422c-9c95-01279bae4b0c.png)


I can submit a patch to the library if it is needed @seuros ?

**Comment by seuros** [comment]
yes

**Comment by jatindhankhar** [comment]
@seuros This should be good right ? 

#65
