### ISSUE TITLE
Support Trilogy database adapter

### ISSUE THREAD

**Issue by joevandyk** [ClosureTree/with_advisory_lock#78]
https://github.blog/2022-08-25-introducing-trilogy-a-new-database-adapter-for-ruby-on-rails/

https://github.com/trilogy-libraries/activerecord-trilogy-adapter

(It's mysql-compatible, I noticed that when testing out trilogy in a project that uses with_advisory_lock, I'm seeing a lot of `.lock-` files)

**Comment by seuros** [comment]
Supported since 5.0.0
